<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-P55NFCV" failures="1" tests="4" name="com.TestNG.Dec_27_2023_Day9_TestNG.AssertionFailures" time="47.655" errors="0" timestamp="2024-01-02T06:52:49 EST" skipped="2">
  <testcase classname="com.TestNG.Dec_27_2023_Day9_TestNG.AssertionFailures" name="login" time="33.791"/>
  <testcase classname="com.TestNG.Dec_27_2023_Day9_TestNG.AssertionFailures" name="logout" time="13.864">
    <failure message=" I just want to fail to test FailAssert so that ContinueButtonOnLogoutPage Test will fail" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  I just want to fail to test FailAssert so that ContinueButtonOnLogoutPage Test will fail
at org.testng.Assert.fail(Assert.java:111)
at com.TestNG.Dec_27_2023_Day9_TestNG.AssertionFailures.logout(AssertionFailures.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logout -->
  <testcase classname="com.TestNG.Dec_27_2023_Day9_TestNG.AssertionFailures" name="continueButtonOnLogoutPage" time="0.000">
    <skipped/>
  </testcase> <!-- continueButtonOnLogoutPage -->
  <testcase classname="com.TestNG.Dec_27_2023_Day9_TestNG.AssertionFailures" name="Logic1">
    <skipped/>
  </testcase> <!-- Logic1 -->
</testsuite> <!-- com.TestNG.Dec_27_2023_Day9_TestNG.AssertionFailures -->
